# Generated by Django 4.1.6 on 2023-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_image_url_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "available"), ("UNAVAILABLE", "unavailable")],
                default="AVAILABLE",
                max_length=200,
            ),
        ),
    ]
