# Generated by Django 3.2.12 on 2023-02-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user_alter_post_author'),
        ('posts', '0007_rename_image_url_post_image'),
    ]

    operations = [
    ]
