# Generated by Django 3.2.12 on 2023-02-22 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230221_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 17, 53, 41, 358242), verbose_name='date published'),
        ),
    ]
