# Generated by Django 4.1.6 on 2023-03-09 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_rating_post_status_user_rating_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 10, 13, 31, 99927), verbose_name='date published'),
        ),
    ]
