# Generated by Django 4.1.6 on 2023-03-09 09:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_rating_count_user_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 10, 36, 22, 871011), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
    ]
