# Generated by Django 4.1.6 on 2023-03-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_status_alter_post_pub_date_rental'),
        ('posts', '0012_rentrequest_post_status_alter_post_image_and_more'),
        ('posts', '0013_auto_20230222_1759'),
        ('posts', '0014_alter_post_pub_date_alter_post_rating_and_more'),
    ]

    operations = [
    ]
