# Generated by Django 4.1.6 on 2023-03-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_category_post_status_alter_post_image_and_more'),
        ('posts', '0015_merge_20230316_1136'),
    ]

    operations = [
    ]
