# Generated by Django 4.1.6 on 2023-03-21 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_merge_20230316_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='review',
            field=models.BooleanField(default=False, verbose_name='review status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 13, 39, 16, 79720), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='end_date',
            field=models.DateField(verbose_name='date returned'),
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='start_date',
            field=models.DateField(verbose_name='date rented'),
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='PENDING', max_length=200),
        ),
    ]
