# Generated by Django 4.1.6 on 2023-03-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_merge_20230321_1333'),
        ('posts', '0016_rentrequest_review_alter_post_pub_date_and_more'),
    ]

    operations = [
    ]
