# Generated by Django 4.1.7 on 2023-03-21 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_status_user_isreported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 59, 48, 138790), verbose_name='date published'),
        ),
    ]
