# Generated by Django 4.1.6 on 2023-03-21 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_post_status_alter_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 15, 20, 2, 150986), verbose_name='date published'),
        ),
    ]
